DROP TABLE IF EXISTS TEMPERATURES;
DROP TABLE IF EXISTS WEATHER;

CREATE TABLE TEMPERATURES
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    weather_id  INT(20) NOT NULL,
    temperature NUMBER(3, 1) NOT NULL
);

CREATE TABLE WEATHER
(
    id    INT AUTO_INCREMENT PRIMARY KEY,
    date  DATE NULL,
    lat   FLOAT,
    lon   FLOAT,
    city  VARCHAR,
    state VARCHAR
);
